### PR TITLE
add support for options verb

### PR DESCRIPTION
**Pull request by frejonb**
Missing `options` method from https://github.com/request/request#requestmethod

### CODE REVIEW

**Comment by akanass** [comment]
Thank you for this PR and use this library.

Why do you want to have `option`? Because this verb is normally used automatically when a `GET` is done.

You will never have an answer in `body` for this verb so I don’t if it’s relevant to add it.

**Comment by frejonb** [comment]
Thanks for the quick reply. I'm migrating a legacy API to `express` using `rx-http-request` and we need to maintain support for calling `options` on its own for some endpoints.

**Comment by akanass** [comment]
Ok I am doing the MR tomorrow morning after reviewing and check if all tests are ok

**Comment by akanass** [comment]
@frejonb `v3.3.0` is published

**Comment by frejonb** [comment]
👍 @akanass

**Pull request merged**
